/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Classes.Player;
import Classes.dbConn;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.OK_OPTION;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
/**
 *
 * @author marco
 */
public class TelaJogoGrande extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     * @throws java.sql.SQLException
     */
    public TelaJogoGrande() throws SQLException {
        this.initComponents();
        this.desenharJogo();
        this.setLocationRelativeTo(null);
    }
   
    dbConn conn = new dbConn();  
    boolean win = false;
    
    private void win() throws SQLException {
        
        if(this.position1.getText() != null){
            this.win(this.position1, this.position2, this.position3);
            this.win(this.position1, this.position4, this.position7);
            this.win(this.position1, this.position5, this.position9);
        }else if(this.position2.getText() != null){
            this.win(this.position2, this.position5, this.position8);
        }else if(this.position3.getText() != null){
            this.win(this.position3, this.position5, this.position7);
            this.win(this.position3, this.position6, this.position9);
        }else if(this.position4.getText() != null){
            this.win(this.position4, this.position5, this.position6);
        }else if(this.position7.getText() != null){
            this.win(this.position7, this.position8, this.position9);
        }            

    }
    
    private void win(JButton position1, JButton position2, JButton position3) throws SQLException {
        if (position1.getText().equals(position2.getText()) && position1.getText().equals(position3.getText())) {
            this.win = true;
            if (JOptionPane.showConfirmDialog(null,position1.getText() + " Win, wanna restart?", position1.getText() + " Win, wanna restart?", YES_NO_OPTION) == YES_OPTION){
                this.dispose();
                this.conn.resetarJogo();
                new TelaJogoGrande().setVisible(true);
            }
            else {
                this.dispose();
            }
        }
    }
    
    private void draw() throws SQLException {
        if (this.position1.getText() != null && this.position2.getText() != null && this.position3.getText() != null && this.position4.getText() != null && this.position5.getText() 
        != null && this.position6.getText() != null && this.position7.getText() != null && this.position8.getText() != null && this.position9.getText() != null && !this.win){
            if (JOptionPane.showConfirmDialog(null, " Draw, Wanna restart?", null, YES_NO_OPTION) == YES_OPTION) {
                this.dispose();
                this.conn.resetarJogo();
                new TelaJogoGrande().setVisible(true);
            }
            else {
                this.dispose();
            }
        }
    } 
                    
    private void desenharJogo() throws SQLException {
        this.conn.getConnection();
        this.position1.setText(this.conn.pegarLetra(1));
        this.position2.setText(this.conn.pegarLetra(2));
        this.position3.setText(this.conn.pegarLetra(3));
        this.position4.setText(this.conn.pegarLetra(4));
        this.position5.setText(this.conn.pegarLetra(5));
        this.position6.setText(this.conn.pegarLetra(6));
        this.position7.setText(this.conn.pegarLetra(7));
        this.position8.setText(this.conn.pegarLetra(8));
        this.position9.setText(this.conn.pegarLetra(9));
    }    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        position9 = new javax.swing.JButton();
        position1 = new javax.swing.JButton();
        position2 = new javax.swing.JButton();
        position3 = new javax.swing.JButton();
        position6 = new javax.swing.JButton();
        position5 = new javax.swing.JButton();
        position4 = new javax.swing.JButton();
        position7 = new javax.swing.JButton();
        position8 = new javax.swing.JButton();
        board = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setMinimumSize(new java.awt.Dimension(730, 637));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SuperTicTacToe");
        getContentPane().add(title);
        title.setBounds(140, 60, 433, 56);

        subTitle.setText("Click in the board to play");
        getContentPane().add(subTitle);
        subTitle.setBounds(290, 130, 150, 16);

        position9.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position9.setBorder(null);
        position9.setContentAreaFilled(false);
        position9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position9ActionPerformed(evt);
            }
        });
        getContentPane().add(position9);
        position9.setBounds(420, 410, 100, 100);

        position1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position1.setBorder(null);
        position1.setContentAreaFilled(false);
        position1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position1ActionPerformed(evt);
            }
        });
        getContentPane().add(position1);
        position1.setBounds(200, 190, 100, 100);

        position2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position2.setBorder(null);
        position2.setContentAreaFilled(false);
        position2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position2.setMaximumSize(new java.awt.Dimension(72, 23));
        position2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position2ActionPerformed(evt);
            }
        });
        getContentPane().add(position2);
        position2.setBounds(320, 190, 80, 100);

        position3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position3.setBorder(null);
        position3.setContentAreaFilled(false);
        position3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position3ActionPerformed(evt);
            }
        });
        getContentPane().add(position3);
        position3.setBounds(420, 190, 100, 100);

        position6.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position6.setBorder(null);
        position6.setContentAreaFilled(false);
        position6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position6ActionPerformed(evt);
            }
        });
        getContentPane().add(position6);
        position6.setBounds(420, 310, 100, 80);

        position5.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position5.setBorder(null);
        position5.setContentAreaFilled(false);
        position5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position5ActionPerformed(evt);
            }
        });
        getContentPane().add(position5);
        position5.setBounds(320, 310, 80, 80);

        position4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position4.setBorder(null);
        position4.setContentAreaFilled(false);
        position4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position4ActionPerformed(evt);
            }
        });
        getContentPane().add(position4);
        position4.setBounds(200, 310, 100, 80);

        position7.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position7.setBorder(null);
        position7.setContentAreaFilled(false);
        position7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position7ActionPerformed(evt);
            }
        });
        getContentPane().add(position7);
        position7.setBounds(200, 410, 100, 100);

        position8.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position8.setBorder(null);
        position8.setContentAreaFilled(false);
        position8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position8ActionPerformed(evt);
            }
        });
        getContentPane().add(position8);
        position8.setBounds(320, 410, 80, 100);

        board.setBackground(new java.awt.Color(255, 255, 255));
        board.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        board.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TicTacToe.png"))); // NOI18N
        board.setToolTipText("");
        board.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        board.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(board);
        board.setBounds(190, 180, 340, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void position1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position1ActionPerformed
        if (this.position1.getText() != null) {
            this.position1.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition1 = new TelaJogoPequeno();
            telaPosition1.setId(1);
            telaPosition1.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position1ActionPerformed

    private void position2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position2ActionPerformed
        if (this.position2.getText() != null) {
            this.position2.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition2 = new TelaJogoPequeno();
            telaPosition2.setId(2);
            telaPosition2.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position2ActionPerformed

    private void position3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position3ActionPerformed
        if (this.position3.getText() != null) {
            this.position3.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition3 = new TelaJogoPequeno();
            telaPosition3.setId(3);
            telaPosition3.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position3ActionPerformed

    private void position4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position4ActionPerformed
        if (this.position4.getText() != null) {
            this.position4.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition4 = new TelaJogoPequeno();
            telaPosition4.setId(4);
            telaPosition4.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position4ActionPerformed

    private void position5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position5ActionPerformed
        if (this.position5.getText() != null) {
            this.position5.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition5 = new TelaJogoPequeno();
            telaPosition5.setId(5);
            telaPosition5.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position5ActionPerformed

    private void position6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position6ActionPerformed
        if (this.position6.getText() != null) {
            this.position6.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition6 = new TelaJogoPequeno();
            telaPosition6.setId(6);
            telaPosition6.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position6ActionPerformed

    private void position7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position7ActionPerformed
        if (this.position7.getText() != null) {
            this.position7.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition7 = new TelaJogoPequeno();
            telaPosition7.setId(7);
            telaPosition7.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position7ActionPerformed

    private void position8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position8ActionPerformed
        if (this.position8.getText() != null) {
            this.position8.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition8 = new TelaJogoPequeno();
            telaPosition8.setId(8);
            telaPosition8.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position8ActionPerformed

    private void position9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position9ActionPerformed
        if (this.position9.getText() != null) {
            this.position9.setEnabled(false);
        }
        else {
            final TelaJogoPequeno telaPosition9 = new TelaJogoPequeno();
            telaPosition9.setId(9);
            telaPosition9.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_position9ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            this.win();
            this.draw();
        }
        catch (SQLException ex) {
            Logger.getLogger(TelaJogoGrande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaJogoGrande().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaJogoGrande.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel board;
    private javax.swing.JButton position1;
    private javax.swing.JButton position2;
    private javax.swing.JButton position3;
    private javax.swing.JButton position4;
    private javax.swing.JButton position5;
    private javax.swing.JButton position6;
    private javax.swing.JButton position7;
    private javax.swing.JButton position8;
    private javax.swing.JButton position9;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
